
import os
import gradio as gr
from dotenv import load_dotenv
from mrag.assistant import Assistant
from mrag.configuration import Configuration
from mrag.utils import logger

log = logger.init(level="DEBUG", save_log=True)


load_dotenv()

UI_PORT: int = int(os.getenv("UI_PORT", "8046"))


log.info("- Load the configuration")

config = Configuration()

log.debug(f"specs path: {config.specs_path}")
log.debug(f"index path: {config.vector_index_path}")

log.info("- Create the assistant instance")
qa_assistant = Assistant(
    docs_path=config.jsons_path,
    specs_path=config.specs_path,
    vector_index_path=config.vector_index_path,
)


def respond(question, history):
    """
    Get the response for a given question using the QA assistant.

    Args:
        question (str): The question to be asked.
        history (list): The list of previous questions and answers.

    Returns:
        str: The response generated by the QA assistant.
    """
    response = qa_assistant.request(question)
    return response


log.info("launch the user interface")
PLACE_HOLDER = "¡Hola!, ¿Qué servicio está buscando?"
BOTH_ICON = "assets/bot.png"
USER_ICON = "assets/user.png"
chatbot = gr.ChatInterface(
    fn=respond,
    chatbot=gr.Chatbot(elem_id="chatbot", height="auto", avatar_images=[USER_ICON, BOTH_ICON]),
    title="",
    textbox=gr.Textbox(placeholder=PLACE_HOLDER, container=False, scale=7),
    clear_btn="Limpiar",
    retry_btn=None,
    undo_btn=None,
    submit_btn="Enviar",
    theme=gr.themes.Default(primary_hue="purple", secondary_hue="indigo"),
)

if __name__ == "__main__":
    chatbot.launch(server_name="0.0.0.0", server_port=UI_PORT)
